platform :ios, '12.0'

target 'WeChat' do
  use_frameworks!

  # Pods for WeChat
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseCore'

  post_install do |installer|
    # Set global deployment target and other build settings
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++14'
          config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end

    # Specific Pod target tweaks
    installer.pods_project.targets.each do |target|

      # Fix for BoringSSL-GRPC warnings
      if target.name == 'BoringSSL-GRPC'
        target.source_build_phase.files.each do |file|
          if file.settings && file.settings['COMPILER_FLAGS']
            flags = file.settings['COMPILER_FLAGS'].split
            flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
            file.settings['COMPILER_FLAGS'] = flags.join(' ')
          end
        end
      end

      # Ensure code signing is disabled
      target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end
